### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by MohamedHmini** [aissam-out/game-of-life#1]
1. consider abstracting the program to incorporate different types of rules which can be specified by the user, i think ppl would love to have a handy and easy to run simulations like this for cellular automata.
2. the frame size is fixed, it would be great if we could navigate.
3. also the it's a bit speedy.

**beautiful tho :smile:**

**Comment by aissam-out** [comment]
> 1. consider abstracting the program to incorporate different types of rules which can be specified by the user, i think ppl would love to have a handy and easy to run simulations like this for cellular automata.
> 2. the frame size is fixed, it would be great if we could navigate.
> 3. also the it's a bit speedy.
> 
> **beautiful tho 😄**

Hey Mohamed! thanks for your comments .. 
Yeah this makes sense. I'll try to add these features as soon as i have some time 🙏
